In [2]:
from google.colab import files
uploaded = files.upload()

ModuleNotFoundError: No module named 'google.colab'

In [ ]:
import pandas as pd

# Replace with your file name if needed
file_name = list(uploaded.keys())[0]

df = pd.read_csv(file_name, sep="\t")
df.head()

,Study ID,Patient ID,Sample ID,Age at Diagnosis,Type of Breast Surgery,Cancer Type,Cancer Type Detailed,Cellularity,Chemotherapy,Pam50 + Claudin-low subtype,...,Relapse Free Status (Months),Relapse Free Status,Number of Samples Per Patient,Sample Type,Sex,3-Gene classifier subtype,TMB (nonsynonymous),Tumor Size,Tumor Stage,Patient's Vital Status
0,brca_metabric,MB-0000,MB-0000,75.65,MASTECTOMY,Breast Cancer,Breast Invasive Ductal Carcinoma,NaN,NO,claudin-low,...,140.500000,0:Not Recurred,1,Primary,Female,ER-/HER2-,0.000000,22.0,2.0,Living
1,brca_metabric,MB-0002,MB-0002,43.19,BREAST CONSERVING,Breast Cancer,Breast Invasive Ductal Carcinoma,High,NO,LumA,...,84.633333,0:Not Recurred,1,Primary,Female,ER+/HER2- High Prolif,2.615035,10.0,1.0,Living
2,brca_metabric,MB-0005,MB-0005,48.87,MASTECTOMY,Breast Cancer,Breast Invasive Ductal Carcinoma,High,YES,LumB,...,153.300000,1:Recurred,1,Primary,Female,NaN,2.615035,15.0,2.0,Died of Disease
3,brca_metabric,MB-0006,MB-0006,47.68,MASTECTOMY,Breast Cancer,Breast Mixed Ductal and Lobular Carcinoma,Moderate,YES,LumB,...,164.933333,0:Not Recurred,1,Primary,Female,NaN,1.307518,25.0,2.0,Living
4,brca_metabric,MB-0008,MB-0008,76.97,MASTECTOMY,Breast Cancer,Breast Mixed Ductal and Lobular Carcinoma,High,YES,LumB,...,18.800000,1:Recurred,1,Primary,Female,ER+/HER2- High Prolif,2.615035,40.0,2.0,Died of Disease

In [ ]:
print(df.columns.tolist())

['Study ID', 'Patient ID', 'Sample ID', 'Age at Diagnosis', 'Type of Breast Surgery', 'Cancer Type', 'Cancer Type Detailed', 'Cellularity', 'Chemotherapy', 'Pam50 + Claudin-low subtype', 'Cohort', 'ER status measured by IHC', 'ER Status', 'Neoplasm Histologic Grade', 'HER2 status measured by SNP6', 'HER2 Status', 'Tumor Other Histologic Subtype', 'Hormone Therapy', 'Inferred Menopausal State', 'Integrative Cluster', 'Primary Tumor Laterality', 'Lymph nodes examined positive', 'Mutation Count', 'Nottingham prognostic index', 'Oncotree Code', 'Overall Survival (Months)', 'Overall Survival Status', 'PR Status', 'Radio Therapy', 'Relapse Free Status (Months)', 'Relapse Free Status', 'Number of Samples Per Patient', 'Sample Type', 'Sex', '3-Gene classifier subtype', 'TMB (nonsynonymous)', 'Tumor Size', 'Tumor Stage', "Patient's Vital Status"]

In [ ]:
# Example mapping (adjust if needed)

selected_cols = [
    'ER status measured by IHC',
    'PR Status',
    'HER2 Status',
    'Tumor Size',
    'Lymph nodes examined positive',
    'Tumor Stage'
]

df = df[selected_cols]
df.head()

,ER status measured by IHC,PR Status,HER2 Status,Tumor Size,Lymph nodes examined positive,Tumor Stage
0,Positve,Negative,Negative,22.0,10.0,2.0
1,Positve,Positive,Negative,10.0,0.0,1.0
2,Positve,Positive,Negative,15.0,1.0,2.0
3,Positve,Positive,Negative,25.0,3.0,2.0
4,Positve,Positive,Negative,40.0,8.0,2.0

In [ ]:
df.columns = [
    'ER',
    'PR',
    'HER2',
    'Tumor_Size',
    'Nodes',
    'Stage'
]

df.head()

        ER        PR      HER2  Tumor_Size  Nodes  Stage
0  Positve  Negative  Negative        22.0   10.0    2.0
1  Positve  Positive  Negative        10.0    0.0    1.0
2  Positve  Positive  Negative        15.0    1.0    2.0
3  Positve  Positive  Negative        25.0    3.0    2.0
4  Positve  Positive  Negative        40.0    8.0    2.0

In [ ]:
def clean_status(x):
    if pd.isna(x):
        return None
    x = str(x).lower()

    if "pos" in x or "+" in x:
        return "Positive"
    elif "neg" in x or "-" in x:
        return "Negative"
    else:
        return None

df['ER'] = df['ER'].apply(clean_status)
df['PR'] = df['PR'].apply(clean_status)
df['HER2'] = df['HER2'].apply(clean_status)

df.head()

         ER        PR      HER2  Tumor_Size  Nodes  Stage
0  Positive  Negative  Negative        22.0   10.0    2.0
1  Positive  Positive  Negative        10.0    0.0    1.0
2  Positive  Positive  Negative        15.0    1.0    2.0
3  Positive  Positive  Negative        25.0    3.0    2.0
4  Positive  Positive  Negative        40.0    8.0    2.0

In [ ]:
df['Tumor_Size'] = pd.to_numeric(df['Tumor_Size'], errors='coerce')
df['Nodes'] = pd.to_numeric(df['Nodes'], errors='coerce')

df.head()

         ER        PR      HER2  Tumor_Size  Nodes  Stage
0  Positive  Negative  Negative        22.0   10.0    2.0
1  Positive  Positive  Negative        10.0    0.0    1.0
2  Positive  Positive  Negative        15.0    1.0    2.0
3  Positive  Positive  Negative        25.0    3.0    2.0
4  Positive  Positive  Negative        40.0    8.0    2.0

In [ ]:
def clean_stage(x):
    if pd.isna(x):
        return None
    x = str(x).upper()

    if "I" in x:
        return "I"
    elif "II" in x:
        return "II"
    elif "III" in x:
        return "III"
    elif "IV" in x:
        return "IV"
    else:
        return None

df['Stage'] = df['Stage'].apply(clean_stage)

df.head()

         ER        PR      HER2  Tumor_Size  Nodes Stage
0  Positive  Negative  Negative        22.0   10.0  None
1  Positive  Positive  Negative        10.0    0.0  None
2  Positive  Positive  Negative        15.0    1.0  None
3  Positive  Positive  Negative        25.0    3.0  None
4  Positive  Positive  Negative        40.0    8.0  None

In [ ]:
df = df.dropna(subset=['ER', 'HER2', 'Nodes'])

df.shape

(1874, 6)

In [ ]:
df['Tumor_Size'] = df['Tumor_Size'] / 10
df.head()

         ER        PR      HER2  Tumor_Size  Nodes Stage
0  Positive  Negative  Negative         2.2   10.0  None
1  Positive  Positive  Negative         1.0    0.0  None
2  Positive  Positive  Negative         1.5    1.0  None
3  Positive  Positive  Negative         2.5    3.0  None
4  Positive  Positive  Negative         4.0    8.0  None

In [ ]:
def assign_stage(row):
    if row['Nodes'] == 0 and row['Tumor_Size'] <= 2:
        return "I"
    elif row['Nodes'] <= 3:
        return "II"
    elif row['Nodes'] > 3:
        return "III"
    else:
        return None

df['Stage'] = df.apply(assign_stage, axis=1)

df.head()

         ER        PR      HER2  Tumor_Size  Nodes Stage
0  Positive  Negative  Negative         2.2   10.0   III
1  Positive  Positive  Negative         1.0    0.0     I
2  Positive  Positive  Negative         1.5    1.0    II
3  Positive  Positive  Negative         2.5    3.0    II
4  Positive  Positive  Negative         4.0    8.0   III

In [ ]:
import numpy as np

# Simple realistic distribution
df['Ki67'] = np.random.choice([10, 15, 20, 30, 40], size=len(df))

df.head()

         ER        PR      HER2  Tumor_Size  Nodes Stage  Ki67
0  Positive  Negative  Negative         2.2   10.0   III    20
1  Positive  Positive  Negative         1.0    0.0     I    10
2  Positive  Positive  Negative         1.5    1.0    II    30
3  Positive  Positive  Negative         2.5    3.0    II    15
4  Positive  Positive  Negative         4.0    8.0   III    30

In [ ]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 1874 entries, 0 to 1984
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ER          1874 non-null   object
 1   PR          1874 non-null   object
 2   HER2        1874 non-null   object
 3   Tumor_Size  1856 non-null   float64
 4   Nodes       1874 non-null   float64
 5   Stage       1874 non-null   object
 6   Ki67        1874 non-null   int64
dtypes: float64(2), int64(1), object(4)
memory usage: 181.7+ KB

         ER        PR      HER2  Tumor_Size  Nodes Stage  Ki67
0  Positive  Negative  Negative         2.2   10.0   III    20
1  Positive  Positive  Negative         1.0    0.0     I    10
2  Positive  Positive  Negative         1.5    1.0    II    30
3  Positive  Positive  Negative         2.5    3.0    II    15
4  Positive  Positive  Negative         4.0    8.0   III    30

In [ ]:
df.to_csv("clean_metabric_cdss.csv", index=False)

files.download("clean_metabric_cdss.csv")

CREATING RULE ENGINE FROM NCCN AND ISMO GUIDELINES

In [ ]:
!pip install pdfplumber spacy nltk
!python -m spacy download en_core_web_sm

Requirement already satisfied: pdfplumber in /usr/local/lib/python3.12/dist-packages (0.11.9)
Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.14)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: pdfminer.six==20251230 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (20251230)
Requirement already satisfied: Pillow>=9.1 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (11.3.0)
Requirement already satisfied: pypdfium2>=4.18.0 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (5.7.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251230->pdfplumber) (3.4.7)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251230->pdfplumber) (43.0.3)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.24.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (26.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.2.25)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.23.0)
Requirement already satisfied: smart-open>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (7.5.1)
Requirement already satisfied: httpx>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber) (2.0.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (2.20.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (2.1.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber) (3.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 101.1 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [ ]:
import pdfplumber
import spacy
import nltk
import re
import json
import pandas as pd
from tqdm import tqdm

nltk.download('punkt')

nlp = spacy.load("en_core_web_sm")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [ ]:
from google.colab import files
uploaded = files.upload()

file_name = list(uploaded.keys())[0]

Saving ISMPO_Guidelines_for_Diagnosis_and_Management_of_E.pdf to ISMPO_Guidelines_for_Diagnosis_and_Management_of_E.pdf
Saving jnccn-article-p331.pdf to jnccn-article-p331.pdf

In [ ]:
from transformers import AutoTokenizer, AutoModel

MODEL_NAME = "emilyalsentzer/Bio_ClinicalBERT"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModel.from_pretrained(MODEL_NAME)

def get_embedding(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)
    outputs = model(**inputs)
    return outputs.last_hidden_state.mean(dim=1).detach().numpy()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/385 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

vocab.txt: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/436M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/436M [00:00<?, ?B/s]

BertModel LOAD REPORT from: emilyalsentzer/Bio_ClinicalBERT
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
def clean_text(text):
    text = re.sub(r'-\s+', '', text)  # fix broken words
    text = re.sub(r'[^\w\s.,%()-]', '', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

In [ ]:
def extract_entities(sentence):
    sentence = sentence.lower()

    entities = {}

    if "her2 positive" in sentence:
        entities["HER2"] = "positive"
    elif "her2 negative" in sentence:
        entities["HER2"] = "negative"

    if "er positive" in sentence:
        entities["ER"] = "positive"
    elif "er negative" in sentence:
        entities["ER"] = "negative"

    if "node positive" in sentence:
        entities["Nodes"] = "positive"
    elif "node negative" in sentence:
        entities["Nodes"] = "negative"

    if "ki67" in sentence:
        if "high" in sentence:
            entities["Ki67"] = "high"
        elif "low" in sentence:
            entities["Ki67"] = "low"

    return entities

In [ ]:
def extract_treatment(sentence):
    sentence = sentence.lower()

    if "chemotherapy" in sentence:
        return "Chemotherapy recommended"
    elif "endocrine" in sentence or "tamoxifen" in sentence:
        return "Endocrine therapy recommended"
    elif "trastuzumab" in sentence or "her2-targeted" in sentence:
        return "HER2-targeted therapy recommended"

    return None

In [ ]:
COMORBIDITIES = ["diabetes", "hypertension", "renal failure", "cardiac disease", "pregnancy"]

def extract_comorbidities(sentence):
    found = []
    for c in COMORBIDITIES:
        if c in sentence.lower():
            found.append(c)
    return found

In [ ]:
def extract_contraindications(sentence):
    sentence = sentence.lower()

    if "contraindicated" in sentence or "avoid" in sentence:
        return True

    return False

In [ ]:
rules = []

for sent in sentences:
    clean_sent = clean_text(sent)

    entities = extract_entities(clean_sent)
    treatment = extract_treatment(clean_sent)

    if entities and treatment:
        rules.append({
            "condition": entities,
            "outcome": treatment,
            "explanation": clean_sent,
            "embedding": get_embedding(clean_sent).tolist()
        })

with open("rules.json", "w") as f:
    json.dump(rules, f, indent=4)

In [ ]:
def recommend_treatment(patient):

    # PRIORITY 1 — HER2
    if patient.get("HER2") == "positive":
        return {
            "recommendation": "HER2-targeted therapy + chemotherapy",
            "reason": "HER2 positive cancers benefit from targeted therapy",
            "confidence": "high"
        }

    # PRIORITY 2 — ER
    if patient.get("ER") == "positive":
        return {
            "recommendation": "Endocrine therapy",
            "reason": "Hormone receptor positive tumors respond to endocrine therapy",
            "confidence": "high"
        }

    # PRIORITY 3 — Nodes
    if patient.get("Nodes") == "positive":
        return {
            "recommendation": "Chemotherapy",
            "reason": "Node positive indicates higher spread risk",
            "confidence": "medium"
        }

    return {
        "recommendation": "Further evaluation needed",
        "reason": "Insufficient data",
        "confidence": "low"
    }

In [ ]:
def adjust_for_comorbidities(recommendation, comorbidities):

    if "cardiac disease" in comorbidities:
        if "HER2-targeted" in recommendation:
            return recommendation + " (Use cautiously due to cardiac risk)"

    if "pregnancy" in comorbidities:
        if "chemotherapy" in recommendation.lower():
            return "Avoid chemotherapy during pregnancy"

    return recommendation

In [ ]:
patient = {
    "HER2": "positive",
    "ER": "negative",
    "Nodes": "positive"
}

comorbidities = ["cardiac disease"]

result = recommend_treatment(patient)

final_recommendation = adjust_for_comorbidities(
    result["recommendation"], comorbidities
)

print({
    "patient": patient,
    "recommendation": final_recommendation,
    "reason": result["reason"],
    "confidence": result["confidence"]
})

{'patient': {'HER2': 'positive', 'ER': 'negative', 'Nodes': 'positive'}, 'recommendation': 'HER2-targeted therapy + chemotherapy (Use cautiously due to cardiac risk)', 'reason': 'HER2 positive cancers benefit from targeted therapy', 'confidence': 'high'}

{'patient': {'HER2': 'positive', 'ER': 'negative', 'Nodes': 'positive'},
'recommendation': 'HER2-targeted therapy + chemotherapy (Use cautiously due to cardiac risk)',

'reason': 'HER2 positive cancers benefit from targeted therapy',

'confidence': 'high'

In [ ]:
import json
from pprint import pprint

# ---- LOAD RULES ----
with open("rules.json", "r") as f:
    rules = json.load(f)

print(f"✅ Total Rules Loaded: {len(rules)}\n")


# ---- SHOW SAMPLE RULES ----
print("🔹 SAMPLE RULES:\n")
for i, r in enumerate(rules[:5]):
    print(f"Rule {i+1}:")
    pprint({
        "condition": r.get("condition"),
        "outcome": r.get("outcome"),
        "explanation": r.get("explanation")[:120] + "..."
    })
    print("-" * 50)


# ---- TEST PATIENT INPUT ----
patient = {
    "ER": "positive",
    "HER2": "negative",
    "Nodes": "negative"
}

print("\n🧍 TEST PATIENT:")
pprint(patient)


# ---- MATCH RULES ----
def match_rules(patient, rules):
    matched = []
    for rule in rules:
        condition = rule.get("condition", {})
        if all(patient.get(k) == v for k, v in condition.items()):
            matched.append(rule)
    return matched


matched = match_rules(patient, rules)

print(f"\n🎯 MATCHED RULES: {len(matched)}\n")

for i, r in enumerate(matched[:5]):
    print(f"Match {i+1}:")
    pprint({
        "condition": r.get("condition"),
        "outcome": r.get("outcome"),
        "explanation": r.get("explanation")[:120] + "..."
    })
    print("-" * 50)


# ---- PICK BEST RULE ----
def get_best_rule(matched_rules):
    if not matched_rules:
        return None
    matched_rules.sort(key=lambda x: len(x.get("condition", {})), reverse=True)
    return matched_rules[0]


best_rule = get_best_rule(matched)

print("\n🏆 BEST RULE:\n")

if best_rule:
    pprint({
        "condition": best_rule.get("condition"),
        "recommendation": best_rule.get("outcome"),
        "explanation": best_rule.get("explanation")
    })
else:
    print("❌ No matching rule found")

✅ Total Rules Loaded: 6

🔹 SAMPLE RULES:

Rule 1:
{'condition': {'ER': 'positive'},
 'explanation': 'intrinsicsubtypesforprognosticationandtherapeuticdeciNuclearstainingbetween10and100%isconsideredpositive '
                'sions(Fig.1).Fo...',
 'outcome': 'Chemotherapy recommended'}
--------------------------------------------------
Rule 2:
{'condition': {'Ki67': 'low'},
 'explanation': 'Score of 2þ is negative Early Breast Cancer '
                'consideredequivocalandfollowedbyreflex '
                'HER2geneamplificationby ISHeitherbydu...',
 'outcome': 'Chemotherapy recommended'}
--------------------------------------------------
Rule 3:
{'condition': {'Nodes': 'positive'},
 'explanation': 'However, for tumors,hadlowriskfordistantrecurrence.21,22 '
                'womenagedlessthan50years,RSscorefrom16to25,did '
                '12-geneassay(End...',
 'outcome': 'Chemotherapy recommended'}
--------------------------------------------------
Rule 4:
{'condition': {'Nodes': 'positive'},
 'explanation': 'thesepatients(n¼120,93%)had T1T2diseaseandwerenodeAPHINITY,80 '
                'a phase III trial randomized 4,800 patients negative(n¼62,...',
 'outcome': 'Chemotherapy recommended'}
--------------------------------------------------
Rule 5:
{'condition': {'Nodes': 'positive'},
 'explanation': 'Inthephase '
                'IIIKEYNOTE-52287trial,patientswithearlyEvidencesuggeststhatanthracycline-basedchemotherapyis '
                'stage,high-risk ...',
 'outcome': 'Chemotherapy recommended'}
--------------------------------------------------

🧍 TEST PATIENT:
{'ER': 'positive', 'HER2': 'negative', 'Nodes': 'negative'}

🎯 MATCHED RULES: 1

Match 1:
{'condition': {'ER': 'positive'},
 'explanation': 'intrinsicsubtypesforprognosticationandtherapeuticdeciNuclearstainingbetween10and100%isconsideredpositive '
                'sions(Fig.1).Fo...',
 'outcome': 'Chemotherapy recommended'}
--------------------------------------------------

🏆 BEST RULE:

{'condition': {'ER': 'positive'},
 'explanation': 'intrinsicsubtypesforprognosticationandtherapeuticdeciNuclearstainingbetween10and100%isconsideredpositive '
                'sions(Fig.1).Forprognosticriskstratificationandpredicandbetween1and10%shouldbereportedaslowpositive.The '
                'tion ofchemotherapy benefit, molecular '
                'profilingofearlylow-positivereportingcategorywith1to10%expressiondoes '
                'stage ER positive, HER-2 negative breast carcinomas is '
                'notapplyto PR.Theresultsshouldexpressoverallpositivity '
                'advised.',
 'recommendation': 'Chemotherapy recommended'}